---
- name: run container
  hosts: all
  tasks:
  - name: pull image
    become: yes
    community.docker.docker_image:
       name: aypas/p0
       source: pull
  - name: run image
    become: yes
    docker_container:
       name: test-p0
       image: aypas/p0
       published_ports: 8080:8080
       state: started